<a href="https://colab.research.google.com/github/Ajay-Kandagatla/DATASCIENCE/blob/main/SCM_Case_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# Import Data Manipulation Library
import pandas as pd
import numpy as np

# Import Data Visualization Library
import seaborn as sns
import matplotlib.pyplot as plt

# Import FilterWarnings Library
import warnings
warnings.filterwarnings('ignore')

In [15]:
# Inport Data Using Pandas
df = pd.read_csv('SCM.csv')

#Shuffle 100% Dataset
df.sample(frac = 1)

# df.head() :It will print top 5 rows
# df.tail() :It will print bottom 5 rows

,Ware_house_ID,WH_Manager_ID,Location_type,WH_capacity_size,zone,WH_regional_zone,num_refill_req_l3m,transport_issue_l1y,Competitor_in_mkt,retail_shop_num,...,electric_supply,dist_from_hub,workers_num,wh_est_year,storage_issue_reported_l3m,temp_reg_mach,approved_wh_govt_certificate,wh_breakdown_l3m,govt_check_l3m,product_wg_ton
1868,WH_101868,EID_51868,Rural,Large,North,Zone 5,1,0,2,5608,...,0,173,41.0,NaN,24,0,B,4,14,28080
10371,WH_110371,EID_60371,Rural,Mid,West,Zone 3,1,0,2,4884,...,1,169,25.0,NaN,21,0,A+,4,19,27137
4936,WH_104936,EID_54936,Rural,Mid,West,Zone 2,1,2,6,4674,...,1,114,37.0,NaN,11,0,A+,4,12,16149
17867,WH_117867,EID_67867,Rural,Mid,West,Zone 2,1,0,3,5457,...,1,147,29.0,NaN,32,0,B+,3,18,38056
2737,WH_102737,EID_52737,Rural,Small,West,Zone 6,1,0,2,5564,...,1,151,25.0,NaN,16,1,A,1,8,23101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19671,WH_119671,EID_69671,Rural,Mid,South,Zone 2,7,0,2,5521,...,0,122,21.0,2015.0,13,0,A,3,22,17057
6094,WH_106094,EID_56094,Rural,Mid,South,Zone 4,8,3,4,6214,...,1,93,38.0,NaN,16,0,A,6,11,20062
16383,WH_116383,EID_66383,Rural,Mid,North,Zone 3,5,0,3,4732,...,1,102,28.0,1998.0,25,0,A,4,19,35131
983,WH_100983,EID_50983,Rural,Mid,West,Zone 2,3,4,2,3509,...,1,261,33.0,2021.0,5,1,A,3,12,7111
21499,WH_121499,EID_71499,Rural,Large,West,Zone 5,3,0,4,4472,...,1,217,30.0,2019.0,6,0,B,1,5,8137

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22150 entries, 0 to 22149
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ware_house_ID                 22150 non-null  object
 1   WH_Manager_ID                 22150 non-null  object
 2   Location_type                 22150 non-null  object
 3   WH_capacity_size              22150 non-null  object
 4   zone                          22150 non-null  object
 5   WH_regional_zone              22150 non-null  object
 6   num_refill_req_l3m            22150 non-null  int64
 7   transport_issue_l1y           22150 non-null  int64
 8   Competitor_in_mkt             22150 non-null  int64
 9   retail_shop_num               22150 non-null  int64
 10  wh_owner_type                 22150 non-null  object
 11  distributor_num               22150 non-null  int64
 12  flood_impacted                22150 non-null  int64
 13  flood_proof                   22150 non-null  int64
 14  electric_supply               22150 non-null  int64
 15  dist_from_hub                 22150 non-null  int64
 16  workers_num                   21273 non-null  float64
 17  wh_est_year                   11605 non-null  float64
 18  storage_issue_reported_l3m    22150 non-null  int64
 19  temp_reg_mach                 22150 non-null  int64
 20  approved_wh_govt_certificate  21345 non-null  object
 21  wh_breakdown_l3m              22150 non-null  int64
 22  govt_check_l3m                22150 non-null  int64
 23  product_wg_ton                22150 non-null  int64
dtypes: float64(2), int64(14), object(8)
memory usage: 4.1+ MB

In [13]:
# Checking Null Values Information Status
# df.isnull().sum() : This Code will give us Number of Missing Values in Each column
# len(df) : This Code will give us total number rows present in dataset.
'''
1. If DataColumn having less than 5% of Missing Values, We can impute with Mean or Median in case of Numerical columns and Imputation with Mode will be for  Categorical Column.
2. If Datacolumn having missing values between 5% to 15% then random value can be imputed or better to replace with Median or use KNN imputer.
3. If Datacolumn having more than 15% of missing values then we can drop that column.

'''
print(df.isnull().sum() / len(df) *100)

Ware_house_ID                    0.000000
WH_Manager_ID                    0.000000
Location_type                    0.000000
WH_capacity_size                 0.000000
zone                             0.000000
WH_regional_zone                 0.000000
num_refill_req_l3m               0.000000
transport_issue_l1y              0.000000
Competitor_in_mkt                0.000000
retail_shop_num                  0.000000
wh_owner_type                    0.000000
distributor_num                  0.000000
flood_impacted                   0.000000
flood_proof                      0.000000
electric_supply                  0.000000
dist_from_hub                    0.000000
workers_num                      3.959368
wh_est_year                     47.607223
storage_issue_reported_l3m       0.000000
temp_reg_mach                    0.000000
approved_wh_govt_certificate     3.634312
wh_breakdown_l3m                 0.000000
govt_check_l3m                   0.000000
product_wg_ton                   0.000000
dtype: float64